"""Synthetic violations for the rare types (v_axis: 10 positives, v_roi: 7), used to train the decision layer.

For every labelled scan, variants with a known violation are generated by synth.py (the spine rotated past
5°, or just inside it; a hip field cut at the top, bottom or side) and labelled by the ТЗ rule. Each variant
is measured exactly like a real scan: by the detector fold model that did NOT see the source scan
(data/train/kp_folds/<tag>), then by decision.spine_measurements / hip_measurements.

Evaluation: the same repeated study-grouped CV as eval_pipeline. Inside each training fold the synthetic
variants of the training scans are added to the fit of the per-type weights, with a weight w; the
percentile reference, the calibration and the threshold stay on real scans only, and every metric is
computed on real held-out scans. w = 0 is the shipped model.

    python scripts/synth_decision.py --tags fix_s100 strong_s100 base_s100 --name ens3
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from PIL import Image
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedGroupKFold

sys.path.insert(0, str(Path(__file__).parent))
from eval_pipeline import best_threshold, metrics  # noqa: E402

from dxaqc import kpmodel as K  # noqa: E402
from dxaqc import synth  # noqa: E402
from dxaqc.decision import Monotone, hip_measurements, spine_measurements  # noqa: E402

KINDS = {"spine": ["tilt", "tilt_ok", "cut_bottom", "cut_top", "cut_top_ok"],
         "hip": ["margin_bottom", "margin_top", "margin_lateral"]}
TYPES = {"spine": ["v_axis", "v_pos"], "hip": ["v_roi"]}
# which violation every generated kind is a positive (or a hard negative) for
KIND_TYPE = {"tilt": "v_axis", "tilt_ok": "v_axis", "cut_bottom": "v_pos", "cut_top": "v_pos",
             "cut_top_ok": "v_pos", "margin_bottom": "v_roi", "margin_top": "v_roi", "margin_lateral": "v_roi"}
# margin_lateral is generated for completeness, but as a third v_roi feature it only hurt (AUC 0.857 -> 0.80
# with synthetic lateral cuts): only 3 of 143 normal hips are below the 2 cm rule, so the experts do not use it.
FEATS = {"v_axis": ["abs_tilt", "curvature"], "v_roi": ["margin_bottom", "margin_top", "margin_lateral"],
         # v_pos ships with one feature (the net's confidence in the iliac crests). A second feature was
         # tried before and did not help on 6 positives; synthetic cuts are what makes it fittable.
         "v_pos": ["crest_conf", "span_vert"]}
EVAL_COLS = {"v_axis": [0, 1], "v_roi": [0, 1], "v_pos": [0, 1]}
SIGNS = {"v_axis": [1, -1], "v_roi": [-1, -1, -1], "v_pos": [-1, -1]}


def spacing(idx, i):
    return float(idx.loc[i, "mm_per_px"]), float(idx.loc[i, "mm_per_px_y"])


def fold_models(tags, region):
    """{scan id: [fold models of every run in tags that left this scan out]} — an ensemble when several."""
    out = {}
    for tag in tags:
        for f in sorted(Path("data/train/kp_folds", tag).glob(f"{region}_f*.pt")):
            ck = torch.load(f, map_location="cpu", weights_only=False)
            net = K.KPNet(len(K.POINTS[region]))
            net.load_state_dict(ck["state_dict"])
            net.eval()
            for i in ck["val_ids"]:
                out.setdefault(i, []).append(net)
    return out


def measure(img, pts_conf, region, side, mm):
    p, conf = pts_conf
    names = K.POINTS["spine" if region == "spine" else "hip"]
    points = {k: (None if np.isnan(q).any() else [float(q[0]), float(q[1])]) for k, q in zip(names, p)}
    conf = {k: float(c) for k, c in zip(names, conf)}
    if region == "spine":
        return spine_measurements(img, points, conf, mm, 0.0)
    return hip_measurements(img, points, conf, side, mm)


def generate(tags, per_kind, seed=0, regions=("spine", "hip"), kinds=None):
    idx = pd.read_csv("data/train/image_index.csv")
    idx["id"] = idx.n.map("{:03d}".format) + "_" + idx.region
    idx = idx.set_index("id")
    kp = json.loads(Path("data/train/keypoints.json").read_text())
    rng = np.random.default_rng(seed)
    rows = []
    for region in regions:
        models = fold_models(tags, region)
        for i, net in sorted(models.items()):
            img = np.asarray(Image.open(f"data/annotation/images/{i}.png"))
            side = i[4:]
            for kind in (kinds or KINDS[region]):
                if kind not in KINDS[region]:
                    continue
                for rep in range(per_kind):
                    try:
                        vt = KIND_TYPE[kind]
                        if region == "spine":
                            simg, skp, lab = synth.spine_sample(img, kp[i]["points"], kind, rng)
                        else:
                            simg, skp, lab = synth.hip_sample(img, kp[i]["points"], side, kind, rng, spacing(idx, i)[0])
                        label = bool(lab[vt])
                    except ValueError:   # e.g. the margin is already below the limit
                        continue
                    (pc,) = K.predict(net, [simg], region, "cpu", flips=[side == "hip_left"])   # net: list = ensemble
                    m = measure(simg, pc, region, side, spacing(idx, i))
                    rows.append({"src": i, "kind": kind, "type": vt, "label": int(label),
                                 **{c: m.get(c) for c in FEATS[vt]}})
        print(f"{region}: {len(rows)} synthetic scans so far", flush=True)
    return pd.DataFrame(rows)


class MonotoneSynth(Monotone):
    """Monotone whose feature weights are also fitted on synthetic scans (weight w per synthetic row).
    Standardisation, percentile reference, calibration: real scans only."""

    def __init__(self, signs, Xs, ys, w):
        super().__init__(signs)
        self.Xs, self.ys, self.w_syn = Xs, ys, w

    def fit(self, X, y):
        Z = X * self.signs
        self.mu, self.sd = Z.mean(0), Z.std(0) + 1e-9
        Z = (Z - self.mu) / self.sd
        if Z.shape[1] > 1:
            Zs = (self.Xs * self.signs - self.mu) / self.sd if len(self.Xs) and self.w_syn > 0 else np.zeros((0, Z.shape[1]))
            ZZ = np.vstack([Z, Zs]); yy = np.concatenate([y, self.ys[:len(Zs)]])
            sw = np.concatenate([np.ones(len(Z)), np.full(len(Zs), self.w_syn)])
            # balance real classes as before; synthetic rows keep their own weight
            cw = np.where(yy == 1, len(y) / (2 * max(y.sum(), 1)), len(y) / (2 * max((y == 0).sum(), 1)))
            w = LogisticRegression(C=1.0, max_iter=2000).fit(ZZ, yy, sample_weight=sw * cw).coef_[0]
            self.w = np.clip(w, 0, None) if (w > 0).any() else np.ones(Z.shape[1])
        else:
            self.w = np.ones(Z.shape[1])
        s = Z @ self.w
        self.ref = np.sort(s)
        self.cal = LogisticRegression(C=10.0, max_iter=2000).fit(self._scale(s)[:, None], y)
        if self.cal.coef_[0, 0] <= 0:
            self.cal.coef_[0, 0] = 1e-3
        return self


def evaluate(tag, syn, weights, seeds=range(300, 310)):
    idx = pd.read_csv("data/train/image_index.csv")
    idx["id"] = idx.n.map("{:03d}".format) + "_" + idx.region
    idx = idx.set_index("id")
    kp = json.loads(Path("data/train/keypoints.json").read_text())
    report = {}
    for region, vts in TYPES.items():
      for vt in vts:
          oof = json.loads(Path(f"data/train/kp_oof_{region}_{tag}.json").read_text())
          ids = [i for i in sorted(oof) if not kp[i]["flags"].get("skip") and not pd.isna(idx.loc[i, "y"])]
          real = []
          for i in ids:
              img = np.asarray(Image.open(f"data/annotation/images/{i}.png"))
              names = K.POINTS[region]
              pc = (np.array([oof[i]["points"][k] or [np.nan, np.nan] for k in names], float),
                    np.array([oof[i]["conf"][k] for k in names], float))
              m = measure(img, pc, region, i[4:], spacing(idx, i))
              real.append([m.get(c) for c in FEATS[vt]])
          X = np.nan_to_num(np.array(real, dtype=float), nan=0.0)
          y = idx.loc[ids, vt].astype(int).to_numpy()
          groups = np.array([int(i[:3]) for i in ids])
          S = syn[syn.src.isin(ids) & (syn.type == vt)]
          Xs_all = np.nan_to_num(S[FEATS[vt]].to_numpy(dtype=float), nan=0.0)
          ys_all, gs_all = S.label.to_numpy(int), S.src.str[:3].astype(int).to_numpy()
          for cols in (EVAL_COLS[vt],):
              signs = [1, -1] if vt == "v_axis" else [-1] * len(cols)
              for w in weights:
                  ms = []
                  for seed in seeds:
                      prob, dec = np.zeros(len(y)), np.zeros(len(y), bool)
                      for tr, va in StratifiedGroupKFold(5, shuffle=True, random_state=seed).split(X, y, groups):
                          keep = np.isin(gs_all, groups[tr])        # synthetic variants of training scans only
                          m = MonotoneSynth(signs, Xs_all[keep][:, cols], ys_all[keep], w).fit(X[tr][:, cols], y[tr])
                          t = best_threshold(y[tr], m.predict_proba(X[tr][:, cols])[:, 1])
                          prob[va] = m.predict_proba(X[va][:, cols])[:, 1]
                          dec[va] = prob[va] >= t
                      ms.append(metrics(y, prob, dec))
                  key = f"{vt} [{'+'.join(FEATS[vt][c] for c in cols)}] w={w}"
                  report[key] = {k: round(float(np.mean([x[k] for x in ms])), 3) for k in ("auc", "pr_auc", "f1", "sens", "spec")}
                  r = report[key]
                  print(f"  {key:62s} AUC {r['auc']:.3f}  PR-AUC {r['pr_auc']:.3f}  F1 {r['f1']:.3f}  "
                        f"sens {r['sens']:.2f}  spec {r['spec']:.2f}", flush=True)
    return report


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tags", nargs="+", required=True, help="detector run(s) whose fold models measure the scans")
    ap.add_argument("--name", default=None, help="name of the (ensemble) detector: kp_oof_<region>_<name>.json; "
                                                 "default: the single tag")
    ap.add_argument("--per-kind", type=int, default=2)
    ap.add_argument("--regions", nargs="+", default=["spine", "hip"],
                    help="generate only these; the file gets the region suffix and is merged by hand")
    ap.add_argument("--kinds", nargs="+", default=None, help="generate only these kinds (see KINDS)")
    ap.add_argument("--suffix", default="", help="suffix of the measurements file, when generating a subset")
    ap.add_argument("--no-eval", action="store_true")
    args = ap.parse_args()
    torch.set_num_threads(2)
    name = args.name or "_".join(args.tags)
    part = "" if len(args.regions) == 2 else "_" + args.regions[0]
    path = Path(f"data/train/synth_meas_{name}{part}{args.suffix}.csv")
    if path.exists():
        syn = pd.read_csv(path)
    else:
        syn = generate(args.tags, args.per_kind, regions=args.regions, kinds=args.kinds)
        syn.to_csv(path, index=False)
    print(syn.groupby(["kind", "label"]).size().to_string())
    if args.no_eval or part:
        return
    # every measurements file of this detector: the kinds of a new violation type are generated separately
    syn = pd.concat([pd.read_csv(f) for f in sorted(Path("data/train").glob(f"synth_meas_{name}*.csv"))],
                    ignore_index=True)
    syn["type"] = syn["type"] if "type" in syn else syn.kind.map(KIND_TYPE)
    syn["type"] = syn["type"].fillna(syn.kind.map(KIND_TYPE))
    report = evaluate(name, syn, weights=[0.0, 0.05, 0.1, 0.2])
    Path(f"data/train/synth_eval_{name}.json").write_text(json.dumps(report, indent=1, ensure_ascii=False))


if __name__ == "__main__":
    main()
